### ISSUE TITLE
Support h2c (http/2 plain) protocol in Netty

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#400]
Add support for h2c protocol in Netty.

The protocol is set on the `HttpServerSettings` instance passed to the server.

All integration tests for the adapter must pass with this protocol.

Check the following Netty examples for reference/examples:
* https://netty.io/4.1/api/io/netty/handler/codec/http2/CleartextHttp2ServerUpgradeHandler.html
* https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http2/helloworld/server/Http2ServerInitializer.java

**Comment by jaguililla** [comment]
Of course you can, and it is highly appreciated. I'm assigning it to you. If you have any doubt, problem or suggestion, just let me know :)

**Comment by izzy-h** [comment]
Thanks for letting me work on this @jaguililla :)

I've made a start following the examples provided but am having some trouble with testing making a request over h2c to the Netty server. The test I've written fails with the error `java.lang.IllegalStateException: Cannot find ClientConnectionFactory to upgrade to Protocol@301a9e[proto=[h2c],nego=false]`

I think this is because the Jetty client the test uses doesn't support upgrading to h2c. I'm not sure if I should try implementing this in the Jetty client. I see there's already an issue open for adding a Netty HTTP client, and I suppose it makes sense to start using that client in the tests, so I don't know if I should wait for the Netty client to be implemented first?

Apologies if I've gone down the wrong track... I'm new to building servers like this so might need a little steering in the right direction. :)

(You can see my changes [here](https://github.com/hexagonkt/hexagon/compare/master...izzy-h:hexagon:support_h2c_in_netty))

**Comment by jaguililla** [comment]
Sorry, I missed the client part in the issue specification.

It would be great to also update the Jetty client to support `h2c`, even being the Netty client in development, as this have to be done sooner or later.

If you could also do the changes on the Jetty client that would be wonderful!

I'll review your changes along the next 3/4 days and give you some feedback.

Thank you for taking care of this issue... This is a tricky one ;)

**Comment by izzy-h** [comment]
Great, thanks for clarifying @jaguililla! I can try updating the Jetty client to support h2c.

**Comment by jaguililla** [comment]
I just took a look at your changes, they look pretty good to me. Aside of one minor cosmetic issue (a three option else-if could be replaced by when).

Looking forward to see the PR :) Thank you very much!

**Comment by jaguililla** [comment]
Hello, I merged your changes in the `feature/h2c` branch and merged the latest changes there, if you want to continue working on the feature, you can pull the changes there. However, if you cannot make it, I'll finish it... At the end, you have it almost complete ;)

**Comment by jaguililla** [comment]
This task will we on-hold, after r3 the remaining work to complete could be done
